### ISSUE TITLE
* Intent

### ISSUE THREAD

**Issue by MatthewPringle** [primaryobjects/chatskills#4]
```
Looking at .intent('*', {
    'slots': {},
    'utterances': [ '{*}' ]
    },
```

Is there anyway to get this running on Alexa? I get the following error "Sorry, the application didn't know what to do with that intent"

**Comment by primaryobjects** [comment]
It appears that Alexa doesn't [support](https://github.com/alexa-js/alexa-app/issues/260#issuecomment-323502614) this at this time. For an example of how get a pseudo wildcard intent, see [here](https://forums.developer.amazon.com/questions/69000/can-wildcards-be-used-in-utterance-statements.html). Thanks.
